#!/bin/sh
set -e

# ---------------------------------------------------------------------------
# Generate nginx.conf from template + ENV
# ---------------------------------------------------------------------------
generate_nginx_conf() {
    sed \
        -e "s|{{NGINX_PORT}}|${NGINX_PORT:-8080}|g" \
        /app/nginx.conf.template > /etc/nginx/nginx.conf
}

# ---------------------------------------------------------------------------
# Generate /etc/crontabs/root from ENV (SCAN_INTERVAL_HOURS)
# ---------------------------------------------------------------------------
generate_crontab() {
    cat > /etc/crontabs/root << 'EOF'
# ssh-access-manager — generated by bootstrap.sh
*/5 * * * * python3 /app/app/collect.py >> /dev/stdout 2>&1
*/5 * * * * python3 /app/app/expire.py >> /dev/stdout 2>&1
EOF
}

# ---------------------------------------------------------------------------
# Generate /etc/msmtprc from template + ENV
# ---------------------------------------------------------------------------
generate_msmtprc() {
    sed \
        -e "s|{{SMTP_HOST}}|${SMTP_HOST:-mail.example.com}|g" \
        -e "s|{{SMTP_PORT}}|${SMTP_PORT:-587}|g" \
        -e "s|{{SMTP_USER}}|${SMTP_USER:-alerts@example.com}|g" \
        -e "s|{{SMTP_PASSWORD}}|${SMTP_PASSWORD:-changeme}|g" \
        -e "s|{{SMTP_FROM}}|${SMTP_FROM:-ssh-manager@example.com}|g" \
        /app/msmtp.conf.template > /etc/msmtprc
    chmod 640 /etc/msmtprc
    chown root:nobody /etc/msmtprc
}

# ---------------------------------------------------------------------------
# Check required environment variables
# ---------------------------------------------------------------------------
_fail=0
if [ -z "${FLASK_SECRET_KEY}" ] || [ "${FLASK_SECRET_KEY}" = "changeme" ]; then
    echo "================================================================" >&2
    echo " ERROR: FLASK_SECRET_KEY is missing or set to 'changeme'." >&2
    echo " Flask sessions cannot be secured." >&2
    echo " Generate a strong key: openssl rand -hex 32" >&2
    echo " Then add it to your .env file:" >&2
    echo "   FLASK_SECRET_KEY=<generated value>" >&2
    echo "================================================================" >&2
    _fail=1
fi
if [ -z "${POSTGRES_PASSWORD}" ] || [ "${POSTGRES_PASSWORD}" = "changeme" ]; then
    echo "================================================================" >&2
    echo " ERROR: POSTGRES_PASSWORD is missing or set to 'changeme'." >&2
    echo " Set a strong password in your .env file:" >&2
    echo "   POSTGRES_PASSWORD=<strong password>" >&2
    echo "================================================================" >&2
    _fail=1
fi
if [ "${_fail}" = "1" ]; then
    exit 1
fi

# ---------------------------------------------------------------------------
# First startup — detected by absence of /data/pg/PG_VERSION
# ---------------------------------------------------------------------------
if [ ! -f /data/pg/PG_VERSION ]; then
    echo "[bootstrap] First startup detected."

    # 1. Create volume directories
    mkdir -p /data/keys /data/pg /data/config

    # 2. Chown postgres first (required before initdb)
    chown postgres:postgres /data/pg
    chmod 700 /data/pg

    # 3. Generate collector ED25519 key pair
    ssh-keygen -t ed25519 \
        -f /data/keys/collector_key \
        -N "" \
        -C "ssh-access-manager@$(hostname)"
    chown nobody:nobody /data/keys/collector_key
    chmod 600 /data/keys/collector_key

    # 4. Create empty known_hosts
    touch /data/keys/known_hosts
    chown nobody:nobody /data/keys/known_hosts
    chmod 644 /data/keys/known_hosts

    # 5. Initialize PostgreSQL cluster
    su -s /bin/sh postgres -c "initdb -D /data/pg --encoding=UTF8 --locale=C"

    # 6. Start PostgreSQL temporarily (local socket only)
    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp' start -w"

    # 7. Create database and user from ENV
    # CREATE DATABASE cannot run in a transaction: two separate calls
    su -s /bin/sh postgres -c "psql -h /tmp -c \"CREATE USER ${POSTGRES_USER:-ssh_manager} WITH PASSWORD '${POSTGRES_PASSWORD:-changeme}';\""
    su -s /bin/sh postgres -c "psql -h /tmp -c \"CREATE DATABASE ${POSTGRES_DB:-ssh_manager} OWNER ${POSTGRES_USER:-ssh_manager};\""

    # 8. Apply SQL schema
    su -s /bin/sh postgres -c \
        "psql -h /tmp -U ${POSTGRES_USER:-ssh_manager} -d ${POSTGRES_DB:-ssh_manager} \
         -f /app/sql/schema.sql"

    # 9. Insert initial administrator from ENV
    # Uses Python+psycopg2 to avoid shell interpolation of hash ($...)
    python3 << 'PYEOF'
import os, psycopg2
from werkzeug.security import generate_password_hash

conn = psycopg2.connect(
    host="/tmp",
    dbname=os.environ.get("POSTGRES_DB", "ssh_manager"),
    user=os.environ.get("POSTGRES_USER", "ssh_manager"),
    password=os.environ.get("POSTGRES_PASSWORD", "changeme"),
)
conn.autocommit = True
cur = conn.cursor()
cur.execute(
    """INSERT INTO administrators (username, email, role, password_hash)
       VALUES (%s, %s, 'sysadmin', %s)
       ON CONFLICT (username) DO NOTHING""",
    (
        os.environ.get("ADMIN_USERNAME", "admin"),
        os.environ.get("ADMIN_EMAIL", "admin@example.com"),
        generate_password_hash(os.environ.get("ADMIN_PASSWORD", "changeme")),
    ),
)
conn.close()
print("[bootstrap] Initial administrator inserted.")
PYEOF

    # 10. Stop temporary PostgreSQL
    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp' stop -w"

    # 11. Generate msmtprc
    generate_msmtprc

    # 12. Generate nginx.conf
    generate_nginx_conf

    # 13. Generate crontab from SCAN_INTERVAL_HOURS
    generate_crontab

    # 14. Display collector public key in logs
    echo ""
    echo "================================================================"
    echo " COLLECTOR PUBLIC KEY — deploy on each remote host"
    echo " via: bash provision-host.sh \"<content below>\""
    echo "================================================================"
    cat /data/keys/collector_key.pub
    echo "================================================================"
    echo ""

else
    echo "[bootstrap] Normal startup (existing data)."

    # Regenerate configuration from ENV on each startup
    generate_nginx_conf
    generate_msmtprc
    generate_crontab
fi

# ---------------------------------------------------------------------------
# Prepare PostgreSQL socket directory (required by Alpine postgresql18)
# ---------------------------------------------------------------------------
mkdir -p /run/postgresql
chown postgres:postgres /run/postgresql

# ---------------------------------------------------------------------------
# Launch supervisord (always last)
# ---------------------------------------------------------------------------
exec /usr/bin/supervisord -c /etc/supervisord.conf
