#!/bin/sh
set -e

# ---------------------------------------------------------------------------
# Generate nginx.conf from template + ENV
# If NGINX_TLS_CERT_PATH and NGINX_TLS_KEY_PATH are set, use the HTTPS
# template (nginx.conf.https.template).  Otherwise use the HTTP-only
# template (nginx.conf.http.template) which contains no SSL directives.
# ---------------------------------------------------------------------------
generate_nginx_conf() {
    _cert="${NGINX_TLS_CERT_PATH:-}"
    _key="${NGINX_TLS_KEY_PATH:-}"
    _port="${NGINX_PORT:-8080}"
    _https_port_suffix=""

    if [ -n "$_cert" ] && [ -n "$_key" ]; then
        if [ "$_port" != "443" ]; then
            _https_port_suffix=":${_port}"
        fi
        sed \
            -e "s|{{NGINX_PORT}}|${_port}|g" \
            -e "s|{{SSL_CERT}}|${_cert}|g" \
            -e "s|{{SSL_KEY}}|${_key}|g" \
            -e "s|{{HTTPS_PORT_SUFFIX}}|${_https_port_suffix}|g" \
            /app/nginx.conf.https.template > /etc/nginx/nginx.conf
        echo "[bootstrap] Nginx configured with TLS on port ${_port} (HTTP redirected to HTTPS)."
    else
        sed "s|{{NGINX_PORT}}|${_port}|g" \
            /app/nginx.conf.http.template > /etc/nginx/nginx.conf
        echo "[bootstrap] Nginx configured in HTTP mode on port ${_port}."
    fi
}

# ---------------------------------------------------------------------------
# Generate a self-signed TLS certificate if cert/key paths are configured
# but the files do not yet exist (idempotent — no-op when files are present).
# ---------------------------------------------------------------------------
generate_tls_cert() {
    _cert="${NGINX_TLS_CERT_PATH:-}"
    _key="${NGINX_TLS_KEY_PATH:-}"

    if [ -z "$_cert" ] || [ -z "$_key" ]; then
        return 0
    fi

    if [ -f "$_cert" ] && [ -f "$_key" ]; then
        echo "[bootstrap] TLS certificate found at ${_cert}."
        return 0
    fi

    echo "[bootstrap] TLS certificate not found — generating a self-signed certificate."
    mkdir -p "$(dirname "$_cert")" "$(dirname "$_key")"
    openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "$_key" \
        -out "$_cert" \
        -days 365 \
        -subj "/CN=ssh-access-manager" \
        -addext "subjectAltName=IP:127.0.0.1,DNS:localhost" 2>/dev/null
    chmod 600 "$_key"
    echo "[bootstrap] Self-signed TLS certificate generated (valid 365 days)."
}

# ---------------------------------------------------------------------------
# Generate /etc/crontabs/root from ENV (SCAN_INTERVAL_HOURS)
# ---------------------------------------------------------------------------
generate_crontab() {
    cat > /etc/crontabs/root << 'EOF'
# ssh-access-manager — generated by bootstrap.sh
*/5 * * * * python3 /app/app/collect.py >> /dev/stdout 2>&1
*/5 * * * * python3 /app/app/expire.py >> /dev/stdout 2>&1
EOF
}

# ---------------------------------------------------------------------------
# Generate /etc/msmtprc dynamically based on SMTP_ENCRYPTION and SMTP_TLSVERIFY
# ---------------------------------------------------------------------------
generate_msmtprc() {
    case "${SMTP_ENCRYPTION:-starttls}" in
        none)
            _tls_block=""
            ;;
        tls)
            if [ "${SMTP_TLSVERIFY:-1}" = "1" ]; then
                _certcheck="on"
            else
                _certcheck="off"
            fi
            _tls_block="tls            on
tls_starttls   off
tls_trust_file /etc/ssl/certs/ca-certificates.crt
tls_certcheck  ${_certcheck}"
            ;;
        starttls|*)
            if [ "${SMTP_TLSVERIFY:-1}" = "1" ]; then
                _certcheck="on"
            else
                _certcheck="off"
            fi
            _tls_block="tls            on
tls_starttls   on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
tls_certcheck  ${_certcheck}"
            ;;
    esac

    if [ -n "${SMTP_USERNAME}" ]; then
        _auth_block="auth           on
user           ${SMTP_USERNAME}
password       ${SMTP_PASSWORD}"
    else
        _auth_block="auth           off"
    fi

    cat > /etc/msmtprc << EOF
defaults
${_auth_block}
${_tls_block}
logfile        /dev/stderr

account        default
host           ${SMTP_HOST:-mail.example.com}
port           ${SMTP_PORT:-587}
from           ${SMTP_FROM:-ssh-manager@example.com}
EOF
    chmod 640 /etc/msmtprc
    chown root:nobody /etc/msmtprc
}

# ---------------------------------------------------------------------------
# Check required environment variables
# ---------------------------------------------------------------------------
_fail=0
if [ -z "${FLASK_SECRET_KEY}" ] || [ "${FLASK_SECRET_KEY}" = "changeme" ]; then
    echo "================================================================" >&2
    echo " ERROR: FLASK_SECRET_KEY is missing or set to 'changeme'." >&2
    echo " Flask sessions cannot be secured." >&2
    echo " Generate a strong key: openssl rand -hex 32" >&2
    echo " Then add it to your .env file:" >&2
    echo "   FLASK_SECRET_KEY=<generated value>" >&2
    echo "================================================================" >&2
    _fail=1
fi
if [ -z "${POSTGRES_PASSWORD}" ] || [ "${POSTGRES_PASSWORD}" = "changeme" ]; then
    echo "================================================================" >&2
    echo " ERROR: POSTGRES_PASSWORD is missing or set to 'changeme'." >&2
    echo " Set a strong password in your .env file:" >&2
    echo "   POSTGRES_PASSWORD=<strong password>" >&2
    echo "================================================================" >&2
    _fail=1
fi
if [ "${_fail}" = "1" ]; then
    exit 1
fi

# ---------------------------------------------------------------------------
# /data/keys/ — per-server keypairs + known_hosts (must exist and be writable
# by nobody, since Flask + crond scans both run as nobody)
# ---------------------------------------------------------------------------
mkdir -p /data/keys/per-server
chown nobody:nobody /data/keys /data/keys/per-server
chmod 755 /data/keys
chmod 700 /data/keys/per-server

# known_hosts must be writable by Flask (nobody) for _fetch_host_key to append
touch /data/keys/known_hosts
chown nobody:nobody /data/keys/known_hosts
chmod 644 /data/keys/known_hosts

# ---------------------------------------------------------------------------
# Legacy global key cleanup — remove the old global collector_key if present
# (upgrade path from pre-per-server-keys architecture)
# ---------------------------------------------------------------------------
if [ -f /data/keys/collector_key ]; then
    echo "[bootstrap] WARNING: Legacy global collector_key found — removing it."
    echo "            Per-server keys are now stored in /data/keys/per-server/"
    rm -f /data/keys/collector_key /data/keys/collector_key.pub
fi

# ---------------------------------------------------------------------------
# First startup — detected by absence of /data/pg/PG_VERSION
# ---------------------------------------------------------------------------
if [ ! -f /data/pg/PG_VERSION ]; then
    echo "[bootstrap] First startup detected."

    # 1. Create volume directories
    mkdir -p /data/keys /data/pg /data/config

    # 2. Chown postgres first (required before initdb)
    chown postgres:postgres /data/pg
    chmod 700 /data/pg

    # 3. Collector key already handled by the guard above

    # 4. Initialize PostgreSQL cluster
    # peer: Unix-socket connections authenticate by OS username (no password needed)
    # scram-sha-256: TCP connections require password (explicit, not relying on distro default)
    su -s /bin/sh postgres -c "initdb -D /data/pg --encoding=UTF8 --locale=C --auth-local=peer --auth-host=scram-sha-256"

    # 5. Start PostgreSQL temporarily (socket + loopback TCP for bootstrap)
    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp -h 127.0.0.1' start -w"

    # 6. Create database and user from ENV (socket, postgres OS user → postgres DB user, peer OK)
    # CREATE DATABASE cannot run in a transaction: two separate calls
    su -s /bin/sh postgres -c "psql -h /tmp -c \"CREATE USER ${POSTGRES_USER:-ssh_manager} WITH PASSWORD '${POSTGRES_PASSWORD:-changeme}';\""
    su -s /bin/sh postgres -c "psql -h /tmp -c \"CREATE DATABASE ${POSTGRES_DB:-ssh_manager} OWNER ${POSTGRES_USER:-ssh_manager};\""

    # 7. Apply SQL schema (TCP, password auth — peer would fail: OS user postgres ≠ DB user ssh_manager)
    PGPASSWORD="${POSTGRES_PASSWORD:-changeme}" \
    su -s /bin/sh postgres -c \
        "psql -h 127.0.0.1 -U ${POSTGRES_USER:-ssh_manager} -d ${POSTGRES_DB:-ssh_manager} \
         -f /app/sql/schema.sql"

    # 8. Insert initial administrator from ENV (TCP, password auth)
    # Uses Python+psycopg2 to avoid shell interpolation of hash ($...)
    python3 << 'PYEOF'
import os, psycopg2
from werkzeug.security import generate_password_hash

conn = psycopg2.connect(
    host="127.0.0.1",
    dbname=os.environ.get("POSTGRES_DB", "ssh_manager"),
    user=os.environ.get("POSTGRES_USER", "ssh_manager"),
    password=os.environ.get("POSTGRES_PASSWORD", "changeme"),
)
conn.autocommit = True
cur = conn.cursor()
cur.execute(
    """INSERT INTO administrators (username, email, role, password_hash)
       VALUES (%s, %s, 'sysadmin', %s)
       ON CONFLICT (username) DO NOTHING""",
    (
        os.environ.get("ADMIN_USERNAME", "admin"),
        os.environ.get("ADMIN_EMAIL", "admin@example.com"),
        generate_password_hash(os.environ.get("ADMIN_PASSWORD", "admin")),
    ),
)
conn.close()
print("[bootstrap] Initial administrator inserted.")
PYEOF

    # 9. Stop temporary PostgreSQL
    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp' stop -w"

    # 10. Generate msmtprc
    generate_msmtprc

    # 11. Generate TLS certificate if enabled
    generate_tls_cert

    # 12. Generate nginx.conf
    generate_nginx_conf

    # 13. Generate crontab
    generate_crontab

else
    echo "[bootstrap] Normal startup (existing data)."

    # Regenerate configuration from ENV on each startup
    generate_tls_cert
    generate_nginx_conf
    generate_msmtprc
    generate_crontab

    # Idempotent schema migrations
    # Use -U postgres (superuser) so peer auth succeeds (OS user postgres == DB user postgres)
    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp' start -w"
    _psql() { su -s /bin/sh postgres -c "psql -h /tmp -U postgres -d ${POSTGRES_DB:-ssh_manager} -c \"$1\""; }

    _psql "ALTER TABLE servers ADD COLUMN IF NOT EXISTS ssh_port INTEGER NOT NULL DEFAULT 22;"
    _psql "ALTER TABLE servers ADD COLUMN IF NOT EXISTS max_sessions INTEGER NOT NULL DEFAULT 2;"
    _psql "ALTER TABLE servers ADD COLUMN IF NOT EXISTS provision_version VARCHAR(64);"
    _psql "ALTER TABLE servers ADD COLUMN IF NOT EXISTS provision_drift BOOLEAN NOT NULL DEFAULT FALSE;"
    _psql "ALTER TABLE servers ADD COLUMN IF NOT EXISTS is_provisioned BOOLEAN NOT NULL DEFAULT FALSE;"
    _psql "ALTER TABLE key_authorizations ADD COLUMN IF NOT EXISTS sam_group VARCHAR(20) CHECK (sam_group IN ('sam-operator', 'sam-pkg', 'sam-root'));"

    # Mark existing active servers as provisioned (they have already passed the activate step)
    _psql "UPDATE servers SET is_provisioned = TRUE WHERE is_active = TRUE AND is_provisioned = FALSE;"

    # Audit log action constraint — versioned, each version is a superset of the previous
    su -s /bin/sh postgres -c "psql -h /tmp -U postgres -d ${POSTGRES_DB:-ssh_manager} -c \
        \"DO \\\$\\\$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_log_action_check_v7') THEN
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check_v6;
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check_v5;
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check_v4;
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check_v3;
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check_v2;
                ALTER TABLE audit_log DROP CONSTRAINT IF EXISTS audit_log_action_check;
                ALTER TABLE audit_log ADD CONSTRAINT audit_log_action_check_v7 CHECK (action IN (
                    'KEY_ADDED','KEY_REVOKED','KEY_EXPIRED','EXPIRY_WARNING',
                    'REQUEST_APPROVED','REQUEST_REJECTED','ANOMALY_DETECTED',
                    'SCAN_COMPLETED','SCAN_FAILED','SCRIPT_DEPLOYED',
                    'SERVER_ADDED','SERVER_DISABLED','SERVER_UPDATED','SERVER_RENAMED',
                    'ADMIN_ADDED','ADMIN_DISABLED','ADMIN_ENABLED','ADMIN_DELETED','ADMIN_UPDATED',
                    'USER_LOCKED','USER_UNLOCKED',
                    'LOGIN_FAILED','LOGIN_BANNED','PASSWORD_RESET',
                    'SERVER_PROVISIONED','SESSION_LIMIT_EXCEEDED',
                    'GROUP_GRANTED','GROUP_REVOKED','GROUP_CHANGED',
                    'PROVISION_UPDATED','PROVISION_UPDATE_FAILED',
                    'COLLECTOR_KEY_GENERATED','COLLECTOR_KEY_ROTATED','COLLECTOR_KEY_ROTATION_FAILED'
                ));
            END IF;
        END \\\$\\\$;\""

    su -s /bin/sh postgres -c "pg_ctl -D /data/pg -o '-k /tmp' stop -w"
fi

# ---------------------------------------------------------------------------
# Prepare PostgreSQL socket directory (required by Alpine postgresql18)
# ---------------------------------------------------------------------------
mkdir -p /run/postgresql
chown postgres:postgres /run/postgresql

# ---------------------------------------------------------------------------
# Launch supervisord (always last)
# ---------------------------------------------------------------------------
exec /usr/bin/supervisord -c /etc/supervisord.conf
