name: Build main image

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build:
    name: Build & push main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          docker build -t ghcr.io/stephdl/ssh-access-manager:main .
          docker push ghcr.io/stephdl/ssh-access-manager:main
